-- Pharma Hub: initial schema (PostgreSQL 14+)
--
-- This migration is the source of truth for the database. prisma/schema.prisma is
-- derived from the database with `npm run db:pull` and never edited by hand, because
-- CHECK constraints, partial indexes and Row Level Security cannot be expressed there.
--
-- One service, one module per integration. This file holds the shared core and the
-- KuantoKusta price-comparison module, which is all of version 1. A later module adds
-- its own prefixed tables and reuses the core unchanged.
--
--   core         stores, store_credentials, api_tokens, job_runs,
--                users, user_sessions, store_memberships, audit_events
--   kuantokusta  kk_store_settings, kk_products, kk_store_offers, kk_page_snapshots,
--                kk_price_comparisons
--
-- Conventions
--   * snake_case identifiers, plural table names, everything in English.
--   * Money is integer cents (EUR). No floats, so differences never drift by a cent.
--   * Time is timestamptz: an absolute instant. The business time zone is Europe/Lisbon,
--     applied when showing, scheduling and reading timestamps that come without an offset.
--   * Ids that leave the service (stores, tokens, runs) are UUIDv7 generated by the
--     application; internal ids are bigint identity.
--   * Fixed sets are text + CHECK, which is easier to extend in a migration than a
--     PostgreSQL enum.
--   * Tenant = store. Every table holding a store's data carries store_id NOT NULL and
--     is protected by Row Level Security (see the end of the file).
--
-- Requires the role pharma_hub_app to exist (db/roles.sql). The migration fails loudly
-- if it does not, which is intended: the application must never run as the table owner.

-- ---------------------------------------------------------------------------
-- Core: tenants, credentials, tokens
-- ---------------------------------------------------------------------------

CREATE TABLE stores (
  id                 uuid        PRIMARY KEY,
  slug               text        NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9-]+$'),
  name               text        NOT NULL,
  -- Product name shown to this store's users in the panel and the plugin, e.g.
  -- "ZincoGroup Hub". The technical name of the service never appears to a client.
  brand_name         text        NOT NULL DEFAULT 'Pharma Hub' CHECK (btrim(brand_name) <> ''),
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

-- Credentials of each external system, one row per store and provider, encrypted by the
-- application (AES-256-GCM) with a master key that lives in the environment, never in
-- the database. Kept out of stores so ordinary queries can never select a secret by accident.
CREATE TABLE store_credentials (
  store_id     uuid        NOT NULL REFERENCES stores (id) ON DELETE CASCADE,
  -- A new integration adds its provider here in a migration.
  provider     text        NOT NULL CHECK (provider IN ('kuantokusta')),
  ciphertext   bytea       NOT NULL,                                 -- secret + GCM tag
  nonce        bytea       NOT NULL CHECK (octet_length(nonce) = 12),
  key_version  smallint    NOT NULL CHECK (key_version > 0),         -- which master key encrypted it
  last_four    text        NOT NULL CHECK (char_length(last_four) = 4), -- shown in the plugin UI
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (store_id, provider)
);

-- Access tokens used by the WordPress plugin. Only the SHA-256 hash is stored: the
-- token is random (256 bits), so a fast hash is enough and a database leak reveals nothing usable.
CREATE TABLE api_tokens (
  id            uuid        PRIMARY KEY,
  store_id      uuid        NOT NULL REFERENCES stores (id) ON DELETE CASCADE,
  token_hash    bytea       NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32),
  token_prefix  text        NOT NULL CHECK (char_length(token_prefix) = 8), -- to recognise a token in UI and logs
  label         text        NOT NULL,
  -- What this token may do. A token for the price report cannot trigger another module's jobs.
  -- New scopes are added here in a migration, so the allowed set is always explicit.
  scopes        text[]      NOT NULL
                            CHECK (cardinality(scopes) > 0
                               AND scopes <@ ARRAY['credentials:write', 'prices:read', 'prices:refresh']),
  created_at    timestamptz NOT NULL DEFAULT now(),
  expires_at    timestamptz,   -- NULL = does not expire
  revoked_at    timestamptz,   -- NULL = active
  last_used_at  timestamptz,   -- NULL = never used
  CHECK (expires_at IS NULL OR expires_at > created_at)
);
CREATE INDEX api_tokens_store_id_idx ON api_tokens (store_id);

-- One execution of a background job for a store: a schedule firing or a button in the
-- plugin. Shared by every module, so progress, history and "one at a time" work the same
-- way for a price collection and for any later module's jobs.
CREATE TABLE job_runs (
  id            uuid        PRIMARY KEY,
  store_id      uuid        NOT NULL REFERENCES stores (id) ON DELETE CASCADE,
  job_type      text        NOT NULL CHECK (job_type IN ('kk_full_collection', 'kk_single_offer_collection')),
  trigger       text        NOT NULL CHECK (trigger IN ('schedule', 'manual')),
  status        text        NOT NULL DEFAULT 'queued'
                            CHECK (status IN ('queued', 'running', 'succeeded', 'partial', 'failed', 'blocked')),
  requested_by  text,       -- who clicked, as reported by the plugin; NULL for scheduled runs
  items_total   integer     NOT NULL DEFAULT 0 CHECK (items_total >= 0),
  items_ok      integer     NOT NULL DEFAULT 0 CHECK (items_ok >= 0),
  items_failed  integer     NOT NULL DEFAULT 0 CHECK (items_failed >= 0),
  error_code    text,       -- machine-readable reason when status is failed or blocked
  queued_at     timestamptz NOT NULL DEFAULT now(),
  started_at    timestamptz,
  finished_at   timestamptz,
  UNIQUE (store_id, id),
  CHECK (items_ok + items_failed <= items_total),
  CHECK ((trigger = 'schedule') = (requested_by IS NULL)),
  CHECK ((status = 'queued') = (started_at IS NULL)),
  CHECK ((status IN ('queued', 'running')) = (finished_at IS NULL)),
  CHECK ((status IN ('failed', 'blocked')) = (error_code IS NOT NULL)),
  CHECK (started_at IS NULL OR started_at >= queued_at),
  CHECK (finished_at IS NULL OR finished_at >= started_at)
);
-- "One at a time": the database itself refuses a second run of an exclusive job type
-- while one is active for the store, so two clicks on "regenerate" cannot overlap.
-- Job types that may run in parallel (a single-offer refresh) are left out of the list.
CREATE UNIQUE INDEX job_runs_one_active_exclusive_run_idx
  ON job_runs (store_id, job_type)
  WHERE status IN ('queued', 'running') AND job_type IN ('kk_full_collection');
-- Latest runs of a store by type, and the cooldown check for manual runs.
CREATE INDEX job_runs_store_type_queued_idx ON job_runs (store_id, job_type, queued_at DESC);

-- ---------------------------------------------------------------------------
-- Core: people (admin panel)
-- ---------------------------------------------------------------------------

-- A person who can sign in to the admin panel, with Google. A row must exist before the
-- first login: this table is the allowlist. There are no passwords.
CREATE TABLE users (
  id             uuid        PRIMARY KEY,
  email          text        NOT NULL UNIQUE CHECK (email = lower(email)),
  -- Google's stable account id ("sub"). NULL until the first login, then the only thing
  -- a login is matched on, so a recycled email address cannot take over the account.
  google_sub     text        UNIQUE,
  display_name   text,
  -- 'admin' may create stores and manage users. Access to a store's data always comes
  -- from store_memberships, also for admins.
  platform_role  text        NOT NULL DEFAULT 'none' CHECK (platform_role IN ('none', 'admin')),
  status         text        NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  last_login_at  timestamptz
);

-- Server-side sessions. Only the SHA-256 hash of the session id is stored.
-- Logging out, or revoking someone's access, deletes the row and takes effect at once.
CREATE TABLE user_sessions (
  id                   uuid        PRIMARY KEY,
  user_id              uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  session_hash         bytea       NOT NULL UNIQUE CHECK (octet_length(session_hash) = 32),
  created_at           timestamptz NOT NULL DEFAULT now(),
  last_seen_at         timestamptz NOT NULL DEFAULT now(),
  idle_expires_at      timestamptz NOT NULL,  -- pushed forward on activity
  absolute_expires_at  timestamptz NOT NULL,  -- never pushed forward
  ip                   inet,
  user_agent           text,
  CHECK (absolute_expires_at > created_at),
  CHECK (idle_expires_at <= absolute_expires_at)
);
CREATE INDEX user_sessions_user_id_idx ON user_sessions (user_id);
-- Cleanup job: delete expired sessions.
CREATE INDEX user_sessions_absolute_expires_at_idx ON user_sessions (absolute_expires_at);

-- Which person may enter which store, and with what role. Each role includes the previous.
--   viewer    reads reports and runs
--   operator  also triggers runs and changes report settings (the usual role for a client)
--   manager   also replaces credentials and issues or revokes plugin tokens
CREATE TABLE store_memberships (
  user_id     uuid        NOT NULL REFERENCES users (id)  ON DELETE CASCADE,
  store_id    uuid        NOT NULL REFERENCES stores (id) ON DELETE CASCADE,
  role        text        NOT NULL CHECK (role IN ('viewer', 'operator', 'manager')),
  created_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, store_id)
);
CREATE INDEX store_memberships_store_id_idx ON store_memberships (store_id);

-- Append-only record of sensitive actions. Rows survive the deletion of the actor and of
-- the store, which is why the actor is also kept as text. Never put a secret in details.
-- The application role gets INSERT and SELECT on this table, not UPDATE or DELETE.
CREATE TABLE audit_events (
  id              bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  occurred_at     timestamptz NOT NULL DEFAULT now(),
  actor_type      text        NOT NULL CHECK (actor_type IN ('user', 'api_token', 'system')),
  actor_user_id   uuid        REFERENCES users (id)      ON DELETE SET NULL,
  actor_token_id  uuid        REFERENCES api_tokens (id) ON DELETE SET NULL,
  actor_label     text        NOT NULL,  -- email or token prefix at the time of the action
  store_id        uuid        REFERENCES stores (id)     ON DELETE SET NULL, -- NULL for platform-level actions
  action          text        NOT NULL CHECK (action ~ '^[a-z_]+\.[a-z_]+$'),   -- e.g. api_token.issued
  target          text,       -- id of the thing acted on, when there is one
  details         jsonb       NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(details) = 'object'),
  ip              inet,
  CHECK (actor_type = 'user'      OR actor_user_id  IS NULL),
  CHECK (actor_type = 'api_token' OR actor_token_id IS NULL)
);
CREATE INDEX audit_events_store_occurred_idx ON audit_events (store_id, occurred_at DESC);
CREATE INDEX audit_events_actor_user_id_idx  ON audit_events (actor_user_id);
CREATE INDEX audit_events_actor_token_id_idx ON audit_events (actor_token_id);

-- ---------------------------------------------------------------------------
-- KuantoKusta module: catalogue
-- ---------------------------------------------------------------------------

-- Per-store settings of this module. A store that only uses another integration has no
-- row here, which keeps KuantoKusta details out of the core stores table.
CREATE TABLE kk_store_settings (
  store_id           uuid        PRIMARY KEY REFERENCES stores (id) ON DELETE CASCADE,
  -- How the store's own offer is identified in the offer list of a KuantoKusta page.
  store_slug         text        NOT NULL UNIQUE,
  -- Learned from the first page where the store is listed; NULL until then.
  seller_id          integer     UNIQUE,
  -- "Easy adjust" threshold: the store is more expensive by at most this many cents.
  easy_adjust_cents  integer     NOT NULL DEFAULT 10 CHECK (easy_adjust_cents >= 0),
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

-- A product page on KuantoKusta. Shared by all stores: it is public data.
CREATE TABLE kk_products (
  id             bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  external_id    bigint      NOT NULL UNIQUE,  -- KuantoKusta's own id, from the page URL: /p/<id>/<slug>
  url            text        NOT NULL,         -- as returned by the Seller API; the slug may change
  name           text        NOT NULL,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);

-- A store's offer on KuantoKusta, synced from the Seller API (GET /v2/kms/offers).
CREATE TABLE kk_store_offers (
  id              bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  store_id        uuid        NOT NULL REFERENCES stores (id) ON DELETE CASCADE,
  product_id      bigint      NOT NULL REFERENCES kk_products (id) ON DELETE RESTRICT,
  kk_offer_ref    text        NOT NULL,  -- "productId" in the Seller API, e.g. p-9-30068
  -- Identifiers as registered on KuantoKusta. Third-party data, so no format CHECK:
  -- the sku may differ from the WooCommerce SKU and both may be missing.
  sku             text,
  ean             text,
  name            text        NOT NULL,
  store_url       text        NOT NULL,  -- product page on the store; last-resort key for the plugin
  price_cents     integer     NOT NULL CHECK (price_cents >= 0),
  stock           integer     NOT NULL CHECK (stock >= 0),
  is_top_box      boolean     NOT NULL,
  -- 'delisted' = the Seller API stopped returning the offer. History is kept.
  listing_status  text        NOT NULL DEFAULT 'listed' CHECK (listing_status IN ('listed', 'delisted')),
  kk_updated_at   timestamptz,           -- "updatedAt" from the Seller API, which has no offset: read as Europe/Lisbon
  first_seen_at   timestamptz NOT NULL DEFAULT now(),
  last_seen_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (store_id, kk_offer_ref),
  -- One offer per store per product: a comparison needs a single store price.
  UNIQUE (store_id, product_id),
  -- Target of the composite foreign keys that keep child rows in the same tenant.
  UNIQUE (store_id, id),
  CHECK (last_seen_at >= first_seen_at)
);
CREATE INDEX kk_store_offers_product_id_idx ON kk_store_offers (product_id);

-- ---------------------------------------------------------------------------
-- KuantoKusta module: collection
-- ---------------------------------------------------------------------------

-- What a KuantoKusta page showed at one moment. Immutable and shared by all stores,
-- so one reading serves every store that sells the product.
CREATE TABLE kk_page_snapshots (
  id              bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  product_id      bigint      NOT NULL REFERENCES kk_products (id) ON DELETE CASCADE,
  fetched_at      timestamptz NOT NULL DEFAULT now(),
  outcome         text        NOT NULL
                              CHECK (outcome IN ('ok', 'not_found', 'blocked', 'no_offer_list', 'http_error', 'network_error')),
  http_status     smallint    CHECK (http_status BETWEEN 100 AND 599),
  -- Third-party payload, always read and written whole, so JSON fits. One element per store:
  -- { storeName, storeSlug, sellerId, priceCents, shippingCents, isHighlighted, isMarketplace }
  offers          jsonb,
  parser_version  smallint    NOT NULL CHECK (parser_version > 0),
  CHECK ((outcome = 'ok') = (offers IS NOT NULL)),
  CHECK (offers IS NULL OR jsonb_typeof(offers) = 'array'),
  CHECK ((outcome = 'network_error') = (http_status IS NULL))
);
-- Latest snapshot of a product, and "is there one fresh enough to reuse".
CREATE INDEX kk_page_snapshots_product_fetched_idx ON kk_page_snapshots (product_id, fetched_at DESC);
-- Retention job: delete snapshots older than 90 days.
CREATE INDEX kk_page_snapshots_fetched_at_idx ON kk_page_snapshots (fetched_at);

-- ---------------------------------------------------------------------------
-- KuantoKusta module: result
-- ---------------------------------------------------------------------------

-- The comparison of one store offer against the other stores, computed from a snapshot.
-- Percentage and "easy adjust" are not stored: they derive from these columns and from
-- kk_store_settings.easy_adjust_cents, so changing the threshold needs no recalculation.
CREATE TABLE kk_price_comparisons (
  id                       bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  store_id                 uuid        NOT NULL,
  run_id                   uuid        NOT NULL,
  store_offer_id           bigint      NOT NULL,
  -- NULL after the raw snapshot is purged by retention; the computed row survives.
  snapshot_id              bigint      REFERENCES kk_page_snapshots (id) ON DELETE SET NULL,
  outcome                  text        NOT NULL
                                       CHECK (outcome IN ('cheapest', 'tied', 'more_expensive', 'only_store', 'no_data')),
  -- Price shown on the page when the store is listed there, otherwise the Seller API price.
  store_price_cents        integer     NOT NULL CHECK (store_price_cents >= 0),
  store_is_listed          boolean,    -- NULL when the page could not be read
  lowest_price_cents       integer     CHECK (lowest_price_cents >= 0),  -- lowest among the OTHER stores
  lowest_store_name        text,
  lowest_store_slug        text,
  -- store_price_cents - lowest_price_cents. Positive: the store is more expensive.
  difference_cents         integer,
  store_position           smallint    CHECK (store_position >= 1),      -- 1 = cheapest; NULL when not listed
  store_count              smallint    CHECK (store_count >= 0),
  -- Same comparison including shipping, when the page informs it.
  store_total_cents        integer     CHECK (store_total_cents >= 0),
  lowest_total_cents       integer     CHECK (lowest_total_cents >= 0),
  lowest_total_store_name  text,
  compared_at              timestamptz NOT NULL DEFAULT now(),
  -- Composite keys: a comparison can only point to a run and an offer of its own store.
  FOREIGN KEY (store_id, run_id)         REFERENCES job_runs (store_id, id)        ON DELETE CASCADE,
  FOREIGN KEY (store_id, store_offer_id) REFERENCES kk_store_offers (store_id, id) ON DELETE CASCADE,
  UNIQUE (run_id, store_offer_id),
  CHECK ((outcome = 'no_data') = (store_is_listed IS NULL)),
  CHECK ((outcome = 'no_data') = (store_count IS NULL)),
  CHECK ((outcome IN ('cheapest', 'tied', 'more_expensive')) = (lowest_price_cents IS NOT NULL)),
  CHECK ((lowest_price_cents IS NULL) = (lowest_store_name IS NULL)),
  CHECK ((lowest_price_cents IS NULL) = (lowest_store_slug IS NULL)),
  CHECK ((lowest_price_cents IS NULL) = (difference_cents IS NULL)),
  CHECK (difference_cents IS NULL OR difference_cents = store_price_cents - lowest_price_cents),
  CHECK (outcome <> 'cheapest'       OR difference_cents < 0),
  CHECK (outcome <> 'tied'           OR difference_cents = 0),
  CHECK (outcome <> 'more_expensive' OR difference_cents > 0),
  CHECK ((lowest_total_cents IS NULL) = (lowest_total_store_name IS NULL))
);
-- The composite foreign keys need no extra index: cascades from job_runs are served by
-- UNIQUE (run_id, store_offer_id) and cascades from kk_store_offers by the index below.
-- Current report (latest comparison per offer) and the price history of one offer.
CREATE INDEX kk_price_comparisons_offer_compared_idx ON kk_price_comparisons (store_offer_id, compared_at DESC);
-- Child side of the snapshot foreign key, used when retention deletes snapshots.
CREATE INDEX kk_price_comparisons_snapshot_id_idx ON kk_price_comparisons (snapshot_id);

-- ---------------------------------------------------------------------------
-- Tenant isolation (Row Level Security)
-- ---------------------------------------------------------------------------
-- The application connects with a role that does NOT own these tables and runs, at the
-- start of every transaction:   SET LOCAL app.current_store_id = '<store uuid>';
-- The store id comes from the authenticated token, never from the request.
-- Without the setting the policy matches nothing, so a forgotten filter returns zero
-- rows instead of another store's data.
--
-- stores, api_tokens, users, user_sessions and store_memberships are left out on purpose:
-- they are read to find out who is calling and which stores that principal may enter,
-- before any store is selected. audit_events is filtered by the application, because it
-- also holds platform-level rows that belong to no store. kk_products and
-- kk_page_snapshots are shared public data.
-- Every new tenant table, in any module, gets the same policy.

CREATE FUNCTION current_store_id() RETURNS uuid
  LANGUAGE sql STABLE
  AS $$ SELECT NULLIF(current_setting('app.current_store_id', true), '')::uuid $$;

ALTER TABLE store_credentials    ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_runs             ENABLE ROW LEVEL SECURITY;
ALTER TABLE kk_store_settings    ENABLE ROW LEVEL SECURITY;
ALTER TABLE kk_store_offers      ENABLE ROW LEVEL SECURITY;
ALTER TABLE kk_price_comparisons ENABLE ROW LEVEL SECURITY;

CREATE POLICY store_isolation ON store_credentials
  USING (store_id = current_store_id()) WITH CHECK (store_id = current_store_id());
CREATE POLICY store_isolation ON job_runs
  USING (store_id = current_store_id()) WITH CHECK (store_id = current_store_id());
CREATE POLICY store_isolation ON kk_store_settings
  USING (store_id = current_store_id()) WITH CHECK (store_id = current_store_id());
CREATE POLICY store_isolation ON kk_store_offers
  USING (store_id = current_store_id()) WITH CHECK (store_id = current_store_id());
CREATE POLICY store_isolation ON kk_price_comparisons
  USING (store_id = current_store_id()) WITH CHECK (store_id = current_store_id());

-- ---------------------------------------------------------------------------
-- Privileges of the application role
-- ---------------------------------------------------------------------------
-- Tables are listed one by one on purpose: a table added later is inaccessible to the
-- application until a migration grants it, instead of being open by default.

GRANT USAGE ON SCHEMA public TO pharma_hub_app;

GRANT SELECT, INSERT, UPDATE, DELETE ON
  stores, store_credentials, api_tokens, job_runs,
  users, user_sessions, store_memberships,
  kk_store_settings, kk_products, kk_store_offers, kk_page_snapshots, kk_price_comparisons
TO pharma_hub_app;

-- Append-only: the application can write and read the audit log, never change it.
GRANT SELECT, INSERT ON audit_events TO pharma_hub_app;
